# Generated by Django 3.2.9 on 2021-11-22 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_certification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='imagefile',
            field=models.FileField(null=True, upload_to='imagefile/%Y/%m/%d'),
        ),
    ]
